from my_agent.WorkflowManager import WorkflowManager

# for deployment on langgraph cloud
graph = WorkflowManager().returnGraph()


host="127.0.0.1"
user="root"
password="Mysqlharsh17@"
database="blinkit"
database="adventureworksdb"



############# BLINKIT QUESTIONS #############

# question = """Calculate the average delivery time for all orders in each city.
# Assumption: Considering the customers whose order status is completed"""


# question = """Find the top 3 customers based on the total order value they have placed.
# Assumption: Considering the customers whose order status is completed"""


# question = """Retrieve the top 3 most frequently ordered products in Mumbai.
# Assumption: Considering the customers whose order status is completed"""

# question = """Identify the number of customers who have not placed an order in the last 30 days."""

# question = """Calculate the total revenue generated by each store.
# Assumption: Considering the revenue from those customers whose order status is
# completed"""

# ***
# question = """Write a SQL query to identify customers who placed only one order in the last 3 months.
# Assumption: Assuming 3 months as 90 days"""

# question = """give a chart of cities with high percentages of customers who ordered only one time."""

# ***
# question = """Analyze the relationship between the distance covered by delivery agents and the
# average delivery time. give chart"""




############## ADVENTUREWORKS QUESTIONS #############

question = 'count the products categories and its proportion'

question = 'count the products subcategories in each product category'

question = 'give average product cost by its subcategory'


graph.invoke({"question": question, "host": host, "user": user, "password": password, 'database': database})